In [2]:
import pandas as pd
import numpy as np

In [3]:
data_folder = "2025-05-23--11h-32m"

In [4]:
df = pd.read_csv(f"../data/{data_folder}/coincidences.csv")
df

,detector_a_name,detector_b_name,arm_a,arm_b,color_a,color_b,delay_a,delay_b,estimation_label,coincidences
0,9,12,TT,TT,white,blue,1.016000e-08,1.172000e-08,DB_H,1679
1,9,11,TT,TR,white,white,1.016000e-08,1.172000e-08,SB,1500
2,9,10,TT,TR,white,blue,1.016000e-08,1.016000e-08,SB,1647
3,11,12,TR,TT,white,blue,1.172000e-08,1.172000e-08,SB,1900
4,10,12,TR,TT,blue,blue,1.016000e-08,1.172000e-08,SB,1994
5,10,11,TR,TR,blue,white,1.016000e-08,1.172000e-08,DB_V,1848
6,1,9,RT,TT,white,white,0.000000e+00,1.016000e-08,C,18
7,1,12,RT,TT,white,blue,0.000000e+00,1.172000e-08,C,31
8,1,11,RT,TR,white,white,0.000000e+00,1.172000e-08,C,35
9,1,10,RT,TR,white,blue,0.000000e+00,1.016000e-08,C,53
10,1,4,RT,RT,white,blue,0.000000e+00,3.910000e-09,DB_H,2423
11,1,7,RT,RR,white,white,0.000000e+00,3.120000e-09,SB,2236
12,1,2,RT,RR,white,blue,0.000000e+00,3.120000e-09,SB,0
13,4,9,RT,TT,blue,white,3.910000e-09,1.016000e-08,C,24
14,4,12,RT,TT,blue,blue,3.910000e-09,1.172000e-08,C,30
15,4,11,RT,TR,blue,white,3.910000e-09,1.172000e-08,C,32
16,4,10,RT,TR,blue,blue,3.910000e-09,1.016000e-08,C,44
17,4,7,RT,RR,blue,white,3.910000e-09,3.120000e-09,SB,2407
18,7,9,RR,TT,white,white,3.120000e-09,1.016000e-08,C,21
19,7,12,RR,TT,white,blue,3.120000e-09,1.172000e-08,C,23
20,7,11,RR,TR,white,white,3.120000e-09,1.172000e-08,C,29
21,7,10,RR,TR,white,blue,3.120000e-09,1.016000e-08,C,42
22,2,9,RR,TT,blue,white,3.120000e-09,1.016000e-08,C,14
23,2,12,RR,TT,blue,blue,3.120000e-09,1.172000e-08,C,0
24,2,11,RR,TR,blue,white,3.120000e-09,1.172000e-08,C,1
25,2,10,RR,TR,blue,blue,3.120000e-09,1.016000e-08,C,25
26,2,4,RR,RT,blue,blue,3.120000e-09,3.910000e-09,SB,1
27,2,7,RR,RR,blue,white,3.120000e-09,3.120000e-09,DB_V,1143

Double bunched events are only resolved half of the time. Therefore, we now throw away half of all non-double-bunched events to recover the expected statistics.

In [5]:
# Reduce the coincidences count for all non-double-bunched rows by 50%
# df[df["estimation_label"] == "C"]["coincidences"] = df[df["estimation_label"] == "C"]["coincidences"] * 0.5
# df[df["estimation_label"] == "SB"]["coincidences"] = df[df["estimation_label"] == "SB"]["coincidences"] * 0.5

df["scaled_coincidences"] = df["coincidences"].astype(float)

df.loc[df["estimation_label"] == "SB", "scaled_coincidences"] = df.loc[df["estimation_label"] == "SB", "coincidences"] * 0.5
df.loc[df["estimation_label"] == "C", "scaled_coincidences"] = df.loc[df["estimation_label"] == "C", "coincidences"] * 0.5

df

,detector_a_name,detector_b_name,arm_a,arm_b,color_a,color_b,delay_a,delay_b,estimation_label,coincidences,scaled_coincidences
0,9,12,TT,TT,white,blue,1.016000e-08,1.172000e-08,DB_H,1679,1679.0
1,9,11,TT,TR,white,white,1.016000e-08,1.172000e-08,SB,1500,750.0
2,9,10,TT,TR,white,blue,1.016000e-08,1.016000e-08,SB,1647,823.5
3,11,12,TR,TT,white,blue,1.172000e-08,1.172000e-08,SB,1900,950.0
4,10,12,TR,TT,blue,blue,1.016000e-08,1.172000e-08,SB,1994,997.0
5,10,11,TR,TR,blue,white,1.016000e-08,1.172000e-08,DB_V,1848,1848.0
6,1,9,RT,TT,white,white,0.000000e+00,1.016000e-08,C,18,9.0
7,1,12,RT,TT,white,blue,0.000000e+00,1.172000e-08,C,31,15.5
8,1,11,RT,TR,white,white,0.000000e+00,1.172000e-08,C,35,17.5
9,1,10,RT,TR,white,blue,0.000000e+00,1.016000e-08,C,53,26.5
10,1,4,RT,RT,white,blue,0.000000e+00,3.910000e-09,DB_H,2423,2423.0
11,1,7,RT,RR,white,white,0.000000e+00,3.120000e-09,SB,2236,1118.0
12,1,2,RT,RR,white,blue,0.000000e+00,3.120000e-09,SB,0,0.0
13,4,9,RT,TT,blue,white,3.910000e-09,1.016000e-08,C,24,12.0
14,4,12,RT,TT,blue,blue,3.910000e-09,1.172000e-08,C,30,15.0
15,4,11,RT,TR,blue,white,3.910000e-09,1.172000e-08,C,32,16.0
16,4,10,RT,TR,blue,blue,3.910000e-09,1.016000e-08,C,44,22.0
17,4,7,RT,RR,blue,white,3.910000e-09,3.120000e-09,SB,2407,1203.5
18,7,9,RR,TT,white,white,3.120000e-09,1.016000e-08,C,21,10.5
19,7,12,RR,TT,white,blue,3.120000e-09,1.172000e-08,C,23,11.5
20,7,11,RR,TR,white,white,3.120000e-09,1.172000e-08,C,29,14.5
21,7,10,RR,TR,white,blue,3.120000e-09,1.016000e-08,C,42,21.0
22,2,9,RR,TT,blue,white,3.120000e-09,1.016000e-08,C,14,7.0
23,2,12,RR,TT,blue,blue,3.120000e-09,1.172000e-08,C,0,0.0
24,2,11,RR,TR,blue,white,3.120000e-09,1.172000e-08,C,1,0.5
25,2,10,RR,TR,blue,blue,3.120000e-09,1.016000e-08,C,25,12.5
26,2,4,RR,RT,blue,blue,3.120000e-09,3.910000e-09,SB,1,0.5
27,2,7,RR,RR,blue,white,3.120000e-09,3.120000e-09,DB_V,1143,1143.0

In [6]:
# Sum up by estimation label
df_sum = df.groupby("estimation_label").agg({"scaled_coincidences": "sum"}).reset_index()
df_sum

  estimation_label  scaled_coincidences
0                C                211.0
1             DB_H               4102.0
2             DB_V               2991.0
3               SB               5842.5

In [7]:
N_C = df_sum[df_sum["estimation_label"] == "C"]["scaled_coincidences"].values[0]
N_SB = df_sum[df_sum["estimation_label"] == "SB"]["scaled_coincidences"].values[0]
N_DB_H = df_sum[df_sum["estimation_label"] == "DB_H"]["scaled_coincidences"].values[0]
N_DB_V = df_sum[df_sum["estimation_label"] == "DB_V"]["scaled_coincidences"].values[0]

N = N_C + N_SB + N_DB_H + N_DB_V
N_C, N_SB, N_DB_H, N_DB_V, N

(np.float64(211.0),
 np.float64(5842.5),
 np.float64(4102.0),
 np.float64(2991.0),
 np.float64(13146.5))

In [8]:
theta_estimate = np.arccos((N_DB_H - N_DB_V) / N)
delta_phi_estimate = np.arctan(np.sqrt(N_C / N_SB))

np.degrees(theta_estimate), np.degrees(delta_phi_estimate)

(np.float64(85.15219831239222), np.float64(10.760102716155503))

In [ ]:
# Save the results to a CSV file
results = pd.DataFrame({
    "estimation_label": ["C", "SB", "DB_H", "DB_V"],
    "scaled_coincidences": [N_C, N_SB, N_DB_H, N_DB_V]
})
results.to_csv(f"../data/{data_folder}/scaled_coincidences.csv", index=False)
# Save the theta and delta_phi estimates to a CSV file
theta_delta_phi = pd.DataFrame({
    "theta_estimate": [np.degrees(theta_estimate)],
    "delta_phi_estimate": [np.degrees(delta_phi_estimate)]
})
theta_delta_phi.to_csv(f"../data/{data_folder}/theta_delta_phi_estimates.csv", index=False)

In [9]:
import qutip as qt

In [11]:
H = qt.basis(2, 0)
V = qt.basis(2, 1)

In [19]:
reconstructed_psi_1 = np.cos(theta_estimate / 2) * H + np.sin(theta_estimate / 2) * V
reconstructed_psi_2 = np.cos(theta_estimate / 2) * H - np.sin(theta_estimate / 2) * np.exp(1j * delta_phi_estimate) * V

In [20]:
reconstructed_psi_1

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.73637938]
 [0.67656885]]

In [18]:
reconstructed_psi_2

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.73637938+0.j        ]
 [-0.66467307-0.12631355j]]